# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Omar/project_7/project_7.cache/wt [current_project]
set_property parent.project_path C:/Users/Omar/project_7/project_7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Omar/project_7/project_7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/ALU.v
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/CU.v
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/DP.v
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/MUX1.v
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/MUX2.v
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/RF.v
  C:/Users/Omar/Desktop/basys3_utility_modules/bcd_to_7seg.v
  C:/Users/Omar/Desktop/basys3_utility_modules/button_debouncer.v
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/calculator_topLevel.v
  C:/Users/Omar/Desktop/basys3_utility_modules/clk_gen.v
  C:/Users/Omar/Desktop/basys3_utility_modules/led_mux.v
  C:/Users/Omar/project_7/project_7.srcs/sources_1/new/calculator_fpga1.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Omar/project_7/project_7.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Omar/project_7/project_7.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top calculator_fpga1 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef calculator_fpga1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file calculator_fpga1_utilization_synth.rpt -pb calculator_fpga1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
